services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=argucheckdb
      - DB_USER=argucheck
      - DB_PASSWORD=admin
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: argucheck
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: argucheckdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://backend:8000"
    container_name: frontend
    volumes:
      - frontend_build:/app/build
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html

volumes:
  postgres_data:
  frontend_build:
